services:
  - type: web
    name: m3u-editor
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_URL
        value: https://m3u-editor.onrender.com
      - key: APP_PORT
        value: "36400"
      - key: ENABLE_POSTGRES
        value: "true"
      - key: REDIS_ENABLED
        value: "true"
      - key: M3U_PROXY_ENABLED
        value: "false"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: m3ue
      - key: DB_USERNAME
        value: m3ue
      - key: DB_PASSWORD
        value: changeme
      - key: PG_DATABASE
        value: m3ue
      - key: PG_USER
        value: m3ue
      - key: PG_PASSWORD
        value: changeme
      - key: REDIS_HOST
        value: localhost
